faiss_db:
  collection_name: "boeing_rag"


embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 20

llm:
  google:
    provider: "google"
    model_name: "models/gemini-2.5-pro-preview-03-25"
    temperature: 0.2
    max_output_tokens: 2048
    